### ISSUE TITLE
Setting SP using vector table

### ISSUE THREAD

**Issue by nscooling** [cpq/bare-metal-programming-guide#15]
is there any particular reason you doing:
```
asm("ldr sp, = _estack");  // Set initial stack pointer
```
rather than
```
__attribute__((section(".vectors"))) void (*tab[16 + 91])(void) = {
  _estack, _reset
};
```

Vector zero should contain the initial stack pointer

**Comment by cpq** [comment]
@nscooling you are correct!

The assembly code is a leftover from the earlier version, where a vector table contained 0 instead of _estack. I'll cleanup the redundant asm instructions.
