### ISSUE TITLE
Question about SysTick

### ISSUE THREAD

**Issue by Korporal** [cpq/bare-metal-programming-guide#39]
I was looking at the code in the project's readme and saw this:

```RCC->APB2ENR |= BIT(14);  ```

I have some low level code in a simple test app for the STM32F407 Discovery board, that sets up SysTick but does nothing at all with the APB2ENR register, whereas your code sets the SYSCFGEN flag in that register. The odd thing is my SysTick works, runs fine. 

Can you help me understand this difference?

**Comment by cpq** [comment]
Setting SYSCFGEN is not required for the SysTick to run, but it is required for other peripherals - for example, Ethernet controller.

Does that answer your question?
