### ISSUE TITLE
Compilation fail on avr-gcc 12.2.2 MacOS

### ISSUE THREAD

**Issue by RandoSY** [cpq/bare-metal-programming-guide#9]
I meant to say ARM-gcc  course :)

**(base) admin@admins-Mac-mini step-0-minimal % make**
arm-none-eabi-gcc main.c  -W -Wall -Wextra -Werror -Wundef -Wshadow -Wdouble-promotion -Wformat-truncation -fno-common -Wconversion -g3 -Os -ffunction-sections -fdata-sections -I. -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16  -Tlink.ld -nostartfiles -nostdlib **--specs nano.specs** -lc -lgcc -Wl,--gc-sections -Wl,-Map=firmware.elf.map -o firmware.elf
/opt/local/lib/gcc/arm-none-eabi/12.2.0/../../../../arm-none-eabi/bin/ld: **cannot find -lc_nano**: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [firmware.elf] Error 1

Plz. advise, thanks!

**Comment by cpq** [comment]
@RandoSY thank you. I've added a Github Action tests on Macos, see https://github.com/cpq/bare-metal-programming-guide/actions - and tests succeed, so search for a problem in your environment / setup. Maybe reinstall ARM GCC? Or delete it and install directly from https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads ?
